image: omalaspinas/archlinux-pandoc:latest

before_script:
   ##
   ## Install ssh-agent if not already installed, it is required by Docker.
   ## (change apt-get to yum if you use an RPM-based image)
   ##
   - 'which ssh-agent || (pacman -S --noconfirm openssh)'
   - 'which rsync || (pacman -S --noconfirm rsync)'
   - pacman -Syyy && pacman -S --noconfirm sdl2


   ##
   ## Run ssh-agent (inside the build environment)
   ##
   - eval $(ssh-agent -s)

   ##
   ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
   ## We're using tr to fix line endings which makes ed25519 keys work
   ## without extra base64 encoding.
   ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
   ##
   - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null

   ##
   ## Create the SSH directory and give it the right permissions
   ##
   - mkdir -p ~/.ssh
   - chmod 700 ~/.ssh

   - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
   - chmod 644 ~/.ssh/known_hosts

   ##
   ## Optionally, if you will be using any Git commands, set the user name and
   ## and email.
   ##
   #- git config --global user.email "user@example.com"
   #- git config --global user.name "User name"


build_only:
  script:
    - make
    - make -C lib
    - make deploy
    - rsync -avz simulation_galaxie malaspinas@129.194.185.180:/www/prog_seq/c_lang/exercices/

build_artifacts:
  script:
    - make
    - make -C lib
  artifacts:
    paths:
      - "galaxie.pdf"
